### ISSUE TITLE
tx test application CRC

### ISSUE THREAD

**Issue by refugeesus** [Lora-net/sx1302_hal#5]
Hello,

Is a CRC always sent with each transmission when using the test_loragw_hal_tx application?

Using a signal generator, I can send LoRa modulated packets, and the receiver (sx1250) can receive with passing CRC. Also I can receive other packets from devices (unknown location) with passing CRC. With the tx test application run from a different DUT, I can receive all packets with correct payload information (except for rssi because I do not have the temperature sensor), but all CRC checks fail. I am trying to debug this issue.

Does the temperature sensor adjustment have any influence on this? (typically I don't think it would)

Thanks,
Robert

**Comment by mcoracin** [comment]
Hello Robert,

No, there is no CRC in packets sent by test_loragw_hal_tx, as you can see here:
https://ch02git1.semtech.com/LoRa-Gateway/sx1302_hal/blob/master/libloragw/tst/test_loragw_hal_tx.c#L500

It is set this way by default, because in LoRaWAN, downlinks have no CRC.

But if you want to set "uplinks" with a gateway for your testing, you have to set this to false.

Best regards,
Michael
