### ISSUE TITLE
How to set Syncword value for proprietary

### ISSUE THREAD

**Issue by pauldeng** [Lora-net/sx1302_hal#59]
Dear @mcoracin, 

In LoRaWAN, the Syncword value 0x34 is for public and 0x12 is for private.

In SX130, the Syncword is defined in loragw_hal.c. It is easy to identify and understand at [here](https://github.com/Lora-net/lora_gateway/blob/master/libloragw/src/loragw_hal.c#L272).

In SX1302, it is defined in loragw_sx1302.c at [here](https://github.com/Lora-net/sx1302_hal/blob/master/libloragw/src/loragw_sx1302.c#L1115). 
However, it is not that easy to understand. It looks to me: 
- to set 0x34, actually 6 and 8 are set to the registers 
- to set 0x12, actually 2 and 4 are set to the registers.

Can I ask what is the algorithm behind it? Is that 0x68 = 0x34 * 2 or 0x6,0x8 = 0x3 * 2, 0x4 * 2.

If I would like to set a proprietary value e.g. 0x2B what should I set here? 0x56 = 0x2B * 2 or 0x4, 0x16 = 0x2 * 2, 0xB * 2

Thanks for your support.

Cheers,
Paul

**Comment by cstratton** [comment]
The recommended syncwords are carefully chosen for distinctness, attempting to use arbitrary values is unlikely to yield good results, especially values chosen without deep understanding of the mechanisms in play.

At a basic level it would appear that the nibbles are being left shifted one position, but there may be more to it than that.

If you really wanted to try other syncwords, you should first read the information about them in all available data sheets, particularly that of the sx126x, sx127x and anything in the less detailed sx1302 and sx1301 sheets.

Then you should probably run some automated tests to see what kind of success rates you get.  Likely you'll want to evaluate not only success at picking up the intended synword, but also the number of intentionally mismatching values that leak through (even the traditional public vs private syncwords are likely to see the occasional mismatched packet leak through - it's basically a crude spam filter to avoid wasting decoder, backhaul, and processing bandwidth, the real check is if the packet matches a known node)

And really you should do this with a node that has a 50 ohm resistor in place of an antenna, so that you can reasonably try a lot of packets per unit time without bothering others.

But really, just use the recommended private syncword and depend on the software filtering to distinguish your traffic from other people's.

**Comment by pauldeng** [comment]
Hi @cstratton ,

Shift 1 bit left does not really work. Checked the datasheets, not much detail about it.

Yeah, I think I need to contact Semtech for support to understand the details behind these carefully selected value.

Thanks for your comprehensive response.

Cheers mate.

**Comment by ywa037** [comment]
Hi @pauldeng 
How to set Syncword value for proprietary In Sx1302

**Comment by cpatulea** [comment]
This worked for me:

```
commit 48619eb92130f3889f927df7f760ffe1851b055f
Author: Catalin Patulea <cronos586@gmail.com>
Date:   Sun Oct 6 15:52:41 2024 -0400

    sx1302_lora_syncword: map private to 0x2b Meshtastic.

diff --git a/libloragw/src/loragw_sx1302.c b/libloragw/src/loragw_sx1302.c
index aa330cd..89a6269 100644
--- a/libloragw/src/loragw_sx1302.c
+++ b/libloragw/src/loragw_sx1302.c
@@ -1129,9 +1129,9 @@ int sx1302_lora_syncword(bool public, uint8_t lora_service_sf) {

     /* LoRa Service modem configuration */
     if ((public == false) || (lora_service_sf == DR_LORA_SF5) || (lora_service_sf == DR_LORA_SF6)) {
-        DEBUG_PRINTF("INFO: configuring LoRa (Service) SF%u with syncword PRIVATE (0x12)\n", lora_service_sf);
-        err |= lgw_reg_w(SX1302_REG_RX_TOP_LORA_SERVICE_FSK_FRAME_SYNCH0_PEAK1_POS, 2);
-        err |= lgw_reg_w(SX1302_REG_RX_TOP_LORA_SERVICE_FSK_FRAME_SYNCH1_PEAK2_POS, 4);
+        DEBUG_PRINTF("INFO: configuring LoRa (Service) SF%u with syncword PRIVATE (0x2b)\n", lora_service_sf);
+        err |= lgw_reg_w(SX1302_REG_RX_TOP_LORA_SERVICE_FSK_FRAME_SYNCH0_PEAK1_POS, 0x2 << 1);
+        err |= lgw_reg_w(SX1302_REG_RX_TOP_LORA_SERVICE_FSK_FRAME_SYNCH1_PEAK2_POS, 0xb << 1);
     } else {
         DEBUG_PRINTF("INFO: configuring LoRa (Service) SF%u with syncword PUBLIC (0x34)\n", lora_service_sf);
         err |= lgw_reg_w(SX1302_REG_RX_TOP_LORA_SERVICE_FSK_FRAME_SYNCH0_PEAK1_POS, 6);
```

Meshtastic default settings (US 906.875 MHz, 250 kHz bandwidth, SF11) receiving about 600 Meshtastic packets per day.

**Comment by radiohound** [comment]
@cpatulea , are you saying you got meshtastic to work on the Maxiot? If so, please explain.

Thank you,

Walter
